ls:
  packages/**:
    .ts: kebab-case
    .js: kebab-case
    .d.ts: kebab-case
  libs/**:
    .ts: kebab-case
    .js: kebab-case
    .d.ts: kebab-case
  crates/**:
    .rs: snake_case
  apps/**:
    .ts: kebab-case
    .js: kebab-case
    .d.ts: kebab-case
    .rs: snake_case
  tools/**:
    .ts: kebab-case
    .js: kebab-case
    .d.ts: kebab-case

ignore:
  - "**/node_modules"
  - "**/tmp"
  - "**/dist"
  - "**/coverage"
  - "**/__generated__"
  - "**/__test__"
  - "**/.terragrunt-cache"
  - "**/.cache"
  - "**/.nx"
