name: "Setup Workspace"
description: "This action install node and cache modules. It uses pnpm as package manager."
inputs:
  working-directory:
    description: "The working directory of your node package"
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v2.4.0
      id: pnpm-install
      with:
        version: 8.7.4

    - uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        node-version-file: .github/.nvmrc
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install
      shell: bash
