name: "Setup Workspace"
description: "This action install node and cache modules. It uses pnpm as package manager."
inputs:
  working-directory:
    description: "The working directory of your node package"
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v2.4.0
      id: pnpm-install
      with:
        version: 8.10.2
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        node-version-file: .github/.nvmrc
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: setup pnpm config registry
      run: pnpm config set registry https://registry.npmjs.org
      shell: bash

    - name: setup pnpm config registry
      run: pnpm install
      shell: bash

    - name: Configure git
      run: |
        git config user.name "${{ env.STORM_WORKER }}"
        git config user.email "${{ env.STORM_WORKER }}@users.noreply.github.com"
        git config lfs.allowincompletepush true
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      shell: bash

    - name: Get appropriate base and head commits for `nx affected` commands
      uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: "main"

    - name: Set appropriate base and head commits for `nx affected` commands
      run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
      shell: bash
