rules:
  template-injection:
    ignore:
      - ci-reusable.yml:80
      - ci.yml:109
  dangerous-triggers:
    ignore:
      - greetings.yml:3:1
  use-trusted-publishing:
    ignore:
      # ignore line 12, column 10 on pypi.yml
      # - pypi.yml:12:10
