rules:
  template-injection:
    ignore:
      # ignore line 100 in ci.yml, any column
      # - ci.yml:100
      # ignore all lines and columns in tests.yml
      # - tests.yml
  use-trusted-publishing:
    ignore:
      # ignore line 12, column 10 on pypi.yml
      # - pypi.yml:12:10
