packages:
  - "tools/**"
  - "packages/**"
  - "devenv-modules"
  - "terraform-modules"
  - "docs/**"
catalog:
  "@ltd/j-toml": "1.38.0"
  "@microsoft/api-extractor": "^7.55.0"
  "@nx/devkit": "22.0.3"
  "@nx/esbuild": "22.0.3"
  "@nx/eslint": "22.0.3"
  "@nx/eslint-plugin": "22.0.3"
  "@nx/jest": "22.0.3"
  "@nx/js": "22.0.3"
  "@nx/node": "^22.0.3"
  "@nx/plugin": "22.0.3"
  "@nx/react": "^22.0.2"
  "@nx/rollup": "^22.0.2"
  "@nx/web": "^22.0.3"
  "@nx/webpack": "^22.0.3"
  "@nx/workspace": "22.0.3"
  "@swc-node/register": "1.10.9"
  "@swc/core": "1.7.26"
  "@swc/helpers": "0.5.13"
  "@types/node": "^22.19.1"
  "@typescript-eslint/eslint-plugin": "^8.46.4"
  "@typescript-eslint/parser": "^8.46.4"
  "@typescript-eslint/utils": "^8.46.4"
  c12: "^2.0.4"
  chalk: "^4.1.2"
  commander: "^12.1.0"
  copyfiles: "2.4.1"
  create-nx-workspace: "^22.0.3"
  cspell: "^8.19.4"
  defu: "6.1.4"
  esbuild: "^0.25.12"
  eslint: "^9.39.1"
  glob: "^11.0.3"
  jest: "30.0.5"
  jest-environment-jsdom: "30.0.5"
  jest-environment-node: "30.0.5"
  jest-resolve: "30.0.5"
  jest-util: "30.0.5"
  jiti: "2.4.2"
  knip: "^5.69.1"
  mlly: "^1.8.0"
  nx: "22.0.3"
  pkg-types: "^1.3.1"
  prettier: "^3.6.2"
  rimraf: "6.0.1"
  rollup: "^4.53.2"
  tsdown: "^0.15.12"
  tslib: "^2.8.1"
  tsup: "8.4.0"
  tsx: "^4.20.6"
  typescript: "^5.9.2"
  typia: "^7.6.4"
  unbuild: "^3.6.1"
  untyped: "^2.0.0"
  wrangler: "^4.33.0"
  yaml: "^2.8.1"
  zod: "^4.1.12"
  zx: "^8.8.5"
linkWorkspacePackages: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@pulumi/docker"
  - "@pulumi/docker-build"
  - "@swc/core"
  - "aws-crt"
  - "bufferutil"
  - "core-js"
  - "core-js-pure"
  - "esbuild"
  - "lefthook"
  - "nx"
  - "oxc-resolver"
  - "protobufjs"
  - "sharp"
  - "unrs-resolver"
  - "workerd"
overrides:
  "@cypress/request": ">=3.0.0"
  "@storm-software/build-tools": "workspace:*"
  "@storm-software/cloudflare-tools": "workspace:*"
  "@storm-software/config": "workspace:*"
  "@storm-software/config-tools": "workspace:*"
  "@storm-software/cspell": "workspace:*"
  "@storm-software/esbuild": "workspace:*"
  "@storm-software/eslint": "workspace:*"
  "@storm-software/git-tools": "workspace:*"
  "@storm-software/k8s-tools": "workspace:*"
  "@storm-software/linting-tools": "workspace:*"
  "@storm-software/markdownlint": "workspace:*"
  "@storm-software/npm-tools": "workspace:*"
  "@storm-software/pnpm-tools": "workspace:*"
  "@storm-software/prettier": "workspace:*"
  "@storm-software/projen": "workspace:*"
  "@storm-software/pulumi-tools": "workspace:*"
  "@storm-software/terraform-tools": "workspace:*"
  "@storm-software/testing-tools": "workspace:*"
  "@storm-software/tools-scripts": "workspace:*"
  "@storm-software/tsconfig": "workspace:*"
  "@storm-software/tsdoc": "workspace:*"
  "@storm-software/tsdown": "workspace:*"
  "@storm-software/tsup": "workspace:*"
  "@storm-software/unbuild": "workspace:*"
  "@storm-software/untyped": "workspace:*"
  "@storm-software/workspace-tools": "workspace:*"
  axios: "1.8.2"
  conventional-changelog-storm-software: "workspace:*"
  create-storm-workspace: "workspace:*"
  got: "14.3.0"
  load-plugin: "6.0.3"
  request: ">=2.88.2"
  tough-cookie: "4.1.4"
patchedDependencies:
  eslint-plugin-pnpm@0.3.0: "patches/eslint-plugin-pnpm@0.3.0.patch"
  eslint-plugin-tsdoc: "patches/eslint-plugin-tsdoc.patch"
  tsup@8.4.0: "patches/tsup@8.4.0.patch"
preferWorkspacePackages: true
