packages:
  - tools/**
  - packages/**
  - devenv-modules
  - terraform-modules
  - docs/**

catalog:
  "@ltd/j-toml": 1.38.0
  "@microsoft/api-extractor": ^7.57.5
  "@nx/devkit": ^22.5.2
  "@nx/esbuild": ^22.5.2
  "@nx/eslint": ^22.5.2
  "@nx/eslint-plugin": ^22.5.2
  "@nx/jest": ^22.5.2
  "@nx/js": ^22.5.2
  "@nx/node": ^22.5.2
  "@nx/plugin": ^22.5.2
  "@nx/web": ^22.5.2
  "@nx/webpack": ^22.5.2
  "@nx/workspace": ^22.5.2
  "@pnpm/types": ^1001.3.0
  "@swc-node/register": 1.11.1
  "@swc/core": 1.15.13
  "@swc/helpers": 0.5.19
  "@types/node": ^25.3.0
  "@typescript-eslint/eslint-plugin": ^8.56.1
  "@typescript-eslint/parser": ^8.56.1
  "@typescript-eslint/utils": ^8.56.1
  prettier-plugin-packagejson: ^3.0.0
  c12: ^2.0.4
  chalk: ^4.1.2
  commander: ^12.1.0
  copyfiles: 2.4.1
  create-nx-workspace: ^22.5.2
  cspell: ^8.19.4
  date-fns: ^4.1.0
  defu: 6.1.4
  esbuild: ^0.27.3
  eslint: ^9.39.3
  glob: ^11.1.0
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  jest-environment-node: 30.2.0
  jest-resolve: 30.2.0
  jest-util: 30.2.0
  jiti: 2.6.1
  knip: ^5.85.0
  mlly: ^1.8.0
  nx: ^22.5.1
  pkg-types: ^1.3.1
  prettier: ^3.8.1
  rimraf: 6.1.3
  rollup: ^4.59.0
  tsdown: ^0.20.3
  tslib: ^2.8.1
  tsup: 8.4.0
  tsx: ^4.21.0
  typia: ^7.6.4
  unbuild: ^3.6.1
  untyped: ^2.0.0
  yaml: ^2.8.2
  zod: ^4.3.6
  zx: ^8.8.5

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@pulumi/docker"
  - "@pulumi/docker-build"
  - "@swc/core"
  - aws-crt
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - lefthook
  - nx
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@cypress/request": ">=3.0.0"
  "@storm-software/build-tools": workspace:*
  "@storm-software/cloudflare-tools": workspace:*
  "@storm-software/config": workspace:*
  "@storm-software/config-tools": workspace:*
  "@storm-software/cspell": workspace:*
  "@storm-software/esbuild": workspace:*
  "@storm-software/eslint": workspace:*
  "@storm-software/git-tools": workspace:*
  "@storm-software/k8s-tools": workspace:*
  "@storm-software/linting-tools": workspace:*
  "@storm-software/markdownlint": workspace:*
  "@storm-software/npm-tools": workspace:*
  "@storm-software/pnpm-tools": workspace:*
  "@storm-software/prettier": workspace:*
  "@storm-software/projen": workspace:*
  "@storm-software/pulumi-tools": workspace:*
  "@storm-software/terraform-tools": workspace:*
  "@storm-software/testing-tools": workspace:*
  "@storm-software/tools-scripts": workspace:*
  "@storm-software/tsconfig": workspace:*
  "@storm-software/tsdoc": workspace:*
  "@storm-software/tsdown": workspace:*
  "@storm-software/tsup": workspace:*
  "@storm-software/unbuild": workspace:*
  "@storm-software/untyped": workspace:*
  "@storm-software/vite": workspace:*
  "@storm-software/workspace-tools": workspace:*
  axios: 1.8.2
  conventional-changelog-storm-software: workspace:*
  create-storm-workspace: workspace:*
  got: 14.3.0
  load-plugin: 6.0.3
  pnpm-plugin-storm-software: workspace:*
  request: ">=2.88.2"
  tough-cookie: 4.1.4

patchedDependencies:
  eslint-plugin-pnpm@0.3.0: patches/eslint-plugin-pnpm@0.3.0.patch
  eslint-plugin-tsdoc: patches/eslint-plugin-tsdoc.patch
  tsup@8.4.0: patches/tsup@8.4.0.patch

preferWorkspacePackages: true

shamefullyHoist: true

shellEmulator: true

supportedArchitectures:
  cpu: [current]

useNodeVersion: 25.5.0

verifyDepsBeforeRun: install
