packages:
  - "tools/*"
  - "crates/*"
  - "packages/*"
  - "terraform-modules/*"
  - "docs/*"

catalog:
  "@microsoft/api-extractor": "^7.48.1"
  "@types/node": "^22.10.2"
  "@nx/devkit": "^20.2.2"
  "@nx/eslint-plugin": "^20.2.2"
  "@nx/eslint": "^20.2.2"
  "@nx/esbuild": "^20.2.2"
  "@nx/node": "^20.2.2"
  "@nx/web": "^20.2.2"
  "@nx/webpack": "^20.2.2"
  "@nx/rollup": "^20.2.2"
  "@nx/jest": "^20.2.2"
  "@nx/js": "^20.2.2"
  "@nx/plugin": "^20.2.2"
  "@nx/react": "^20.2.2"
  "@nx/workspace": "^20.2.2"
  "create-nx-workspace": "^20.2.2"
  "@swc-node/register": "1.10.9"
  "@swc/core": "1.7.26"
  "@swc/helpers": "0.5.13"
  "nx": "^20.2.2"
  "prettier": "^3.3.3"
  "tsup": "^8.3.5"
  "typia": "^7.5.0"
  "typescript": "^5.7.2"
  "esbuild": "^0.24.0"
  "copyfiles": "2.4.1"
  "rimraf": "5.0.7"
