packages:
  - tools/**
  - crates/**
  - packages/**
  - devenv-modules
  - terraform-modules
  - docs/**
catalog:
  "@microsoft/api-extractor": ^7.48.1
  "@types/node": ^22.10.2
  "@nx/devkit": ^21.4.1
  "@nx/eslint-plugin": ^21.4.1
  "@nx/eslint": ^21.4.1
  "@nx/esbuild": ^21.4.1
  "@nx/node": ^21.4.1
  "@nx/web": ^21.4.1
  "@nx/webpack": ^21.4.1
  "@nx/rollup": ^21.4.1
  "@nx/jest": ^21.4.1
  "@nx/js": ^21.4.1
  "@nx/plugin": ^21.4.1
  "@nx/react": ^21.4.1
  "@nx/workspace": ^21.4.1
  create-nx-workspace: ^21.4.1
  "@swc-node/register": 1.10.9
  "@swc/core": 1.7.26
  "@swc/helpers": 0.5.13
  nx: ^21.4.1
  prettier: ^3.5.1
  tsup: 8.4.0
  typia: ^7.5.0
  typescript: ^5.9.2
  jest: 30.0.5
  jest-environment-jsdom: 30.0.5
  jest-environment-node: 30.0.5
  jest-util: 30.0.5
  jest-resolve: 30.0.5
  esbuild: ^0.25.0
  eslint: ^9.35.0
  copyfiles: 2.4.1
  rimraf: 6.0.1
  c12: ^2.0.0-beta.2
  pkg-types: ^1.3.1
  "@ltd/j-toml": 1.38.0
  zod: ^4.0.2
  rollup: ^4.29.1
  tslib: ^2.6.3
  "@typescript-eslint/eslint-plugin": ^8.35.0
  "@typescript-eslint/parser": ^8.35.0
  "@typescript-eslint/utils": ^8.35.0
  knip: ^5.25.2
  unbuild: ^3.2.0
  commander: ^12.1.0
  chalk: ^4.1.2
  defu: 6.1.4
  yaml: ^2.8.1
  cspell: ^8.17.3
  tsdown: 0.5.3
  untyped: ^1.5.2
  wrangler: ^4.33.0
  glob: ^11.0.1
  jiti: ^2.4.2
  tsx: ^4.19.2
  zx: ^8.5.2
linkWorkspacePackages: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@pulumi/docker"
  - "@pulumi/docker-build"
  - "@swc/core"
  - aws-crt
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - lefthook
  - nx
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
overrides:
  "@cypress/request": ">=3.0.0"
  "@storm-software/build-tools": workspace:*
  "@storm-software/cloudflare-tools": workspace:*
  "@storm-software/config": workspace:*
  "@storm-software/config-tools": workspace:*
  "@storm-software/eslint": workspace:*
  "@storm-software/git-tools": workspace:*
  "@storm-software/k8s-tools": workspace:*
  "@storm-software/pulumi-tools": workspace:*
  "@storm-software/linting-tools": workspace:*
  "@storm-software/markdownlint": workspace:*
  "@storm-software/npm-tools": workspace:*
  "@storm-software/projen": workspace:*
  "@storm-software/prettier": workspace:*
  "@storm-software/pnpm-tools": workspace:*
  "@storm-software/untyped": workspace:*
  "@storm-software/esbuild": workspace:*
  "@storm-software/tsdown": workspace:*
  "@storm-software/unbuild": workspace:*
  "@storm-software/terraform-tools": workspace:*
  "@storm-software/testing-tools": workspace:*
  "@storm-software/tsconfig": workspace:*
  "@storm-software/tsdoc": workspace:*
  "@storm-software/workspace-tools": workspace:*
  "@storm-software/cspell": workspace:*
  "@storm-software/tools-scripts": workspace:*
  axios: 1.8.2
  create-storm-workspace: workspace:*
  got: 14.3.0
  load-plugin: 6.0.3
  request: ">=2.88.2"
  tough-cookie: 4.1.4
patchedDependencies:
  eslint-plugin-pnpm@0.3.0: patches/eslint-plugin-pnpm@0.3.0.patch
  tsup@8.4.0: patches/tsup@8.4.0.patch
  eslint-plugin-tsdoc: patches/eslint-plugin-tsdoc.patch
preferWorkspacePackages: true
