packages:
  - "tools/*"
  - "crates/*"
  - "packages/*"
  - "terraform-modules"
  - "docs/*"

catalog:
  "@microsoft/api-extractor": "^7.48.1"
  "@types/node": "^22.10.2"
  "@nx/devkit": "^20.3.1"
  "@nx/eslint-plugin": "^20.3.1"
  "@nx/eslint": "^20.3.1"
  "@nx/esbuild": "^20.3.1"
  "@nx/node": "^20.3.1"
  "@nx/web": "^20.3.1"
  "@nx/webpack": "^20.3.1"
  "@nx/rollup": "^20.3.1"
  "@nx/jest": "^20.3.1"
  "@nx/js": "^20.3.1"
  "@nx/plugin": "^20.3.1"
  "@nx/react": "^20.3.1"
  "@nx/workspace": "^20.3.1"
  "create-nx-workspace": "^20.3.1"
  "@swc-node/register": "1.10.9"
  "@swc/core": "1.7.26"
  "@swc/helpers": "0.5.13"
  "nx": "^20.3.1"
  "prettier": "^3.3.3"
  "tsup": "8.3.5"
  "typia": "^7.5.0"
  "typescript": "^5.7.2"
  "esbuild": "^0.24.0"
  "eslint": "^9.12.0"
  "copyfiles": "2.4.1"
  "rimraf": "6.0.1"
  "c12": "^2.0.0-beta.2"
  "pkg-types": "^1.1.1"
  "zod": "^3.24.0"
  "rollup": "^4.29.1"
  "tslib": "^2.6.3"
  "unbuild": "^3.2.0"
  "commander": "^12.1.0"
  "chalk": "^4.1.2"
  "defu": "6.1.4"
  "read-yaml-file": "2.1.0"
  "cspell": "8.8.4"
  "tsdown": "0.5.3"
  "untyped": "^1.5.2"
  "glob": "^11.0.1"
  "jiti": "^2.4.2"
