# Get help on options with `rustfmt --help=config`
# Please keep these in alphabetical order.
edition = "2021"
tab_spaces = 2
group_imports = "StdExternalCrate"
imports_granularity = "Module"
merge_derives = false
version = "Two"

# This is also the setting used by [rustc](https://github.com/rust-lang/rust/blob/master/rustfmt.toml)
use_small_heuristics = "Max"

# Use field initialize shorthand if possible
use_field_init_shorthand = true
