
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface BaseExecutorSchema {
 /**
  * Output Path
  * 
  * The output path for the build
  * 
  * 
  * @format path
 */
 outputPath?: string,
}

