
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface BaseGeneratorSchema {
 /**
  * Directory
  * 
  * The directory to create the library in
  * 
 */
 directory?: string,
}

