// Generated by @storm-software/untyped
// Do not edit this file directly

export interface InitGeneratorSchema {
  /**
   * Directory
   *
   * The directory to initialize the workspace in
   *
   */
  directory?: string;

  /**
   * Skip Format
   *
   * Skip formatting the generated files
   *
   */
  skipFormat?: boolean;
}
