
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface InitGeneratorSchema {
 /**
  * Base Generator
  * 
  * A type definition for the base Generator schema
  * 
 */
 default?: {
  /**
   * Directory
   * 
   * The directory to create the library in
   * 
  */
  directory?: string,
 },

 /**
  * Directory
  * 
  * The directory to initialize the workspace in
  * 
 */
 directory?: string,

 /**
  * Skip Format
  * 
  * Skip formatting the generated files
  * 
 */
 skipFormat?: boolean,
}

