
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface NpmPublishExecutorSchema {
 /**
  * Package Root
  * 
  * The path to the package root
  * 
  * 
  * @format path
 */
 packageRoot?: string,

 /**
  * Registry
  * 
  * The URL of the registry to publish to
  * 
  * @default "https://registry.npmjs.org/"
 */
 registry?: string,

 /**
  * Tag
  * 
  * The tag to publish with
  * 
  * @default "latest"
 */
 tag?: string,

 /**
  * Version
  * 
  * The version to publish. If not provided, the version from package.json will be used
  * 
 */
 version?: string,

 /**
  * One Time Password (OTP)
  * 
  * The one time password (OTP) for two-factor authentication
  * 
 */
 otp?: string,

 /**
  * Dry Run
  * 
  * Perform a dry run
  * 
  * @default false
 */
 dryRun?: boolean,

 /**
  * First Release
  * 
  * Publish the first release
  * 
  * @default false
 */
 firstRelease?: boolean,
}

