
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface NpmPublishExecutorSchema {
 /**
  * Package Root
  * 
  * The path to the package root
  * 
  * 
  * @format path
 */
 packageRoot?: string,

 /**
  * Registry
  * 
  * The registry to publish to
  * 
  * @default "https://registry.npmjs.org/"
 */
 registry?: string,

 /**
  * Tag
  * 
  * The tag to publish with
  * 
  * @default "latest"
 */
 tag?: string,

 /**
  * One Time Password
  * 
  * The one time password
  * 
 */
 otp?: number,

 /**
  * Dry Run
  * 
  * Perform a dry run
  * 
  * @default false
 */
 dryRun?: boolean,

 /**
  * First Release
  * 
  * Publish the first release
  * 
  * @default false
 */
 firstRelease?: boolean,
}

