import fs from "node:fs/promises";

const configNames = [
  "storm/disables",
  "storm/ignores",
  "storm/imports",
  "storm/javascript",
  "storm/jsdoc",
  "storm/jsx",
  "storm/next",
  "storm/node",
  "storm/promise",
  "storm/react",
  "storm/react-perf",
  "storm/regexp",
  "storm/storybook",
  "storm/test",
  "storm/typescript",
  "storm/unicorn"
] as const;

const dts = `// This file is auto-generated by scripts/typegen.ts.\nexport type ConfigNames = ${configNames.map(i => `'${i}'`).join(" | ")};\n`;

await fs.writeFile("src/typegen.d.ts", dts);
