
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface ConfigSchemaGeneratorSchema {
 /**
  * Output File
  * 
  * The file to write the schema to
  * 
 */
 outputFile?: string,
}

