// Generated by @storm-software/untyped
// Do not edit this file directly

export interface ConfigSchemaGeneratorSchema {
  /**
   * Directory
   *
   * The directory to create the library in
   *
   */
  directory?: string;

  /**
   * Output File
   *
   * The file to write the schema to
   *
   * @default "{workspaceRoot}/storm-workspace.schema.json"
   */
  outputFile?: string;
}
