
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface BrowserLibraryGeneratorSchema {
 /**
  * Directory
  * 
  * The directory to create the library in
  * 
 */
 directory: string,

 /**
  * Name
  * 
  * The name of the library
  * 
 */
 name: string,

 /**
  * Description
  * 
  * The description of the library
  * 
 */
 description?: string,

 /**
  * Build Executor
  * 
  * The executor to use for building the library
  * 
  * @default "@storm-software/workspace-tools:unbuild"
 */
 buildExecutor?: string,

 /**
  * Platform
  * 
  * The platform to target with the library
  * 
  * @default "browser"
  * 
  * @enum browser,neutral
 */
 platform?: string,

 /**
  * Import Path
  * 
  * The import path for the library
  * 
 */
 importPath?: string,

 /**
  * Tags
  * 
  * The tags for the library
  * 
 */
 tags?: string,

 /**
  * Unit Test Runner
  * 
  * The unit test runner to use
  * 
  * 
  * @enum jest,vitest,none
 */
 unitTestRunner?: string,

 /**
  * Test Environment
  * 
  * The test environment to use
  * 
  * 
  * @enum jsdom,node
 */
 testEnvironment?: string,

 /**
  * Pascal Case Files
  * 
  * Use PascalCase for file names
  * 
  * @default false
 */
 pascalCaseFiles?: boolean,

 /**
  * Strict
  * 
  * Enable strict mode
  * 
  * @default true
 */
 strict?: boolean,

 /**
  * Publishable
  * 
  * Make the library publishable
  * 
  * @default false
 */
 publishable?: boolean,

 /**
  * Buildable
  * 
  * Make the library buildable
  * 
  * @default true
 */
 buildable?: boolean,
}

