// Generated by @storm-software/untyped
// Do not edit this file directly

export interface TypeSchema {
  /** @default ["**\/*untyped.ts",null] */
  createNodesV2?: Array<string | Function>;

  /** @default "storm-software/typescript/tsup" */
  name?: string;
}
