
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface CommandPublishExecutorSchema {
 /**
  * Command
  * 
  * The shell command to run to publish the package
  * 
 */
 command?: string,

 /**
  * Commands
  * 
  * Shell commands to run to publish the package
  * 
 */
 commands?: Array<string>,

 /**
  * Working Directory
  * 
  * The working directory to run the publish command in. Defaults to the project root.
  * 
  * 
  * @format path
 */
 cwd?: string,

 /**
  * Dry Run
  * 
  * When true, log the commands that would be run without executing them
  * 
  * @default false
 */
 dryRun?: boolean,
}

