
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface PresetGeneratorSchema {
 /**
  * Name
  * 
  * The name of the workspace
  * 
 */
 name: string,

 /**
  * Organization
  * 
  * The organization of the workspace
  * 
 */
 organization: string,

 /**
  * Include Apps
  * 
  * Include apps in the workspace
  * 
 */
 includeApps: boolean,

 /**
  * Include Rust
  * 
  * Include Rust support in the workspace
  * 
 */
 includeRust: boolean,

 /**
  * Namespace
  * 
  * The namespace of the workspace
  * 
 */
 namespace: string,

 /**
  * Description
  * 
  * The description of the workspace
  * 
 */
 description: string,

 /**
  * Repository URL
  * 
  * The URL of the repository
  * 
 */
 repositoryUrl: string,

 /**
  * Nx Cloud
  * 
  * Nx Cloud configuration
  * 
 */
 nxCloud: string,

 /**
  * Mode
  * 
  * The mode of the Nx client
  * 
 */
 mode: string,

 /**
  * Package Manager
  * 
  * The package manager to use
  * 
 */
 packageManager: string,
}

