
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface PresetGeneratorSchema {
 /**
  * Directory
  * 
  * The directory to create the library in
  * 
 */
 directory: string,

 /**
  * Name
  * 
  * The name of the workspace
  * 
 */
 name: string,

 /**
  * Organization
  * 
  * The organization of the workspace
  * 
  * @default "storm-software"
 */
 organization?: string,

 /**
  * Include Apps
  * 
  * Include apps in the workspace
  * 
  * @default true
 */
 includeApps?: boolean,

 /**
  * Include Rust
  * 
  * Include Rust support in the workspace
  * 
  * @default false
 */
 includeRust?: boolean,

 /**
  * Namespace
  * 
  * The namespace of the workspace
  * 
  * @default "storm-software"
 */
 namespace?: string,

 /**
  * Description
  * 
  * The description of the workspace
  * 
 */
 description?: string,

 /**
  * Repository URL
  * 
  * The URL of the repository
  * 
 */
 repositoryUrl?: string,

 /**
  * Nx Cloud
  * 
  * Nx Cloud configuration
  * 
 */
 nxCloud?: string,

 /**
  * Mode
  * 
  * The mode of the Nx client
  * 
 */
 mode?: string,

 /**
  * Package Manager
  * 
  * The package manager to use
  * 
  * @default "pnpm"
  * 
  * @enum npm,pnpm,yarn,bun
 */
 packageManager?: string,
}

