
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface InitGeneratorSchema {
 /**
  * Skip Format
  * 
  * Skip formatting the generated files
  * 
 */
 skipFormat?: boolean,
}

