# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE:

DEFAULT_BRANCH: main

# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHFMT
  - CLOUDFORMATION_CFN_LINT
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - JSON_V8R
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
  - TERRAFORM_TFLINT
  - YAML_YAMLLINT

FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES|generators/*/files)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|generators/*/files)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true

# Install plugin for list handling.
JSON_PRETTIER_PRE_COMMANDS:
  - command: "npm install @storm-software/prettier"
    cwd: "workspace"

# CLOUDFORMATION_CFN_LINT_CONFIG_FILE: '.cfnlintrc'
# CLOUDFORMATION_CFN_LINT_FILE_EXTENSIONS: [".yml", ".yaml"]

EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: ".ecrc.json"

MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: "-q"
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false

SPELL_CSPELL_ARGUMENTS: "--gitignore --no-progress --show-suggestions"
SPELL_CSPELL_FILE_EXTENSIONS: ["*"]

TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN

YAML_YAMLLINT_CONFIG_FILE: "https://raw.githubusercontent.com/storm-software/storm-ops/refs/heads/main/packages/linting-tools/src/yamllint/.yamllint.yml"

SARIF_REPORTER: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
EMAIL_REPORTER: false
JSON_REPORTER: true

GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
