import { StormConfig } from "@storm-software/config";
import { writeTrace } from "@storm-software/config-tools/logger/console";
import { Path } from "glob";
import { writeFile } from "node:fs/promises";
import { generateTypes, Schema } from "untyped";
import { getOutputFile } from "../utilities";

export function generateDeclaration(schema: Schema) {
  return `
// Generated by @storm-software/untyped
// Do not edit this file directly

${generateTypes(schema, {
  addExport: true,
  interfaceName: `${schema.title?.replaceAll(" ", "") || "Type"}Schema`
})}

`;
}

export function generateDeclarationFile(
  schema: Schema,
  file: Path,
  config?: StormConfig
) {
  const declarations = getOutputFile(file, "d.ts");
  writeTrace(`Writing type declaration file ${declarations}`, config);

  return writeFile(declarations, generateDeclaration(schema));
}
