import { StormConfig } from "@storm-software/config";
import {
  writeError,
  writeTrace,
} from "@storm-software/config-tools/logger/console";
import { Path } from "glob";
import { writeFile } from "node:fs/promises";
import { generateTypes, Schema } from "untyped";
import { getOutputFile } from "../utilities";

export function generateDeclaration(schema: Schema) {
  return `
// Generated by @storm-software/untyped
// Do not edit this file directly

${generateTypes(schema, {
  addExport: true,
  partial: true,
  interfaceName: `${schema.title?.replaceAll(" ", "") || "Type"}Schema`,
})}

`;
}

export function generateDeclarationFile(
  schema: Schema,
  file: Path,
  config?: StormConfig,
) {
  try {
    const declarations = getOutputFile(file, "d.ts");
    writeTrace(`Writing type declaration file ${declarations}`, config);

    return writeFile(declarations, generateDeclaration(schema));
  } catch (error) {
    writeError(
      `Error writing declaration file for ${file.name}

Error:
${error?.message ? error.message : JSON.stringify(error)}${
        error?.stack
          ? `
Stack Trace: ${error.stack}`
          : ""
      }

Parsed schema:
${JSON.stringify(schema)}
`,
      config,
    );

    throw error;
  }
}
