import {
  writeError,
  writeTrace
} from "@storm-software/config-tools/logger/console";
import type { StormWorkspaceConfig } from "@storm-software/config/types";
import type { Path } from "glob";
import { writeFile } from "node:fs/promises";
import { generateTypes, type Schema } from "untyped";
import { getOutputFile } from "../utilities";

/**
 * Generate a TypeScript declaration type from a TypeScript schema.
 *
 * @param schema - The TypeScript schema to convert.
 * @param generatedBy - The tool that generated the declaration.
 * @returns The generated Declaration content.
 */
export function generateDeclaration(
  schema: Schema,
  generatedBy = "@storm-software/untyped"
) {
  return `
// Generated by ${generatedBy}
// Do not edit this file directly

${generateTypes(schema, {
  addExport: true,
  partial: true,
  interfaceName: `${schema.title?.replaceAll(" ", "") || "Type"}Schema`
})}

`;
}

/**
 * Generate a TypeScript declaration type from a TypeScript schema.
 *
 * @param schema - The TypeScript schema to convert.
 * @param file - The file to write the declaration to.
 * @param generatedBy - The tool that generated the declaration.
 * @param config - The workspace configuration.
 * @returns A promise that resolves when the file has been written.
 */
export function generateDeclarationFile(
  schema: Schema,
  file: Path,
  generatedBy = "@storm-software/untyped",
  config?: StormWorkspaceConfig
) {
  try {
    const declarations = getOutputFile(file, "d.ts");
    writeTrace(`Writing type declaration file ${declarations}`, config);

    return writeFile(declarations, generateDeclaration(schema, generatedBy));
  } catch (error) {
    writeError(
      `Error writing declaration file for ${file.name}

Error:
${error?.message ? error.message : JSON.stringify(error)}${
        error?.stack
          ? `
Stack Trace: ${error.stack}`
          : ""
      }

Parsed schema:
${JSON.stringify(schema)}
`,
      config
    );

    throw error;
  }
}
