import {
  writeError,
  writeTrace
} from "@storm-software/config-tools/logger/console";
import type { StormWorkspaceConfig } from "@storm-software/config/types";
import type { Path } from "glob";
import { writeFile } from "node:fs/promises";
import type { Schema } from "untyped";
import { getOutputFile } from "../utilities";

/**
 * Generate a Markdown file from a TypeScript schema.
 *
 * @param schema - The TypeScript schema to convert.
 * @param generatedBy - The tool that generated the Markdown.
 * @returns The generated Markdown content.
 */
export function generateMarkdown(
  schema: Schema,
  generatedBy = "@storm-software/untyped"
) {
  return `
<!-- Generated by ${generatedBy} -->
<!-- Do not edit this file directly -->

${generateMarkdownLevel(schema, schema.title || "", "#").join("\n")}

`;
}

function generateMarkdownLevel(schema: Schema, title: string, level: string) {
  const lines: string[] = [];

  lines.push(`${level} ${title}`);

  if (schema.type === "object") {
    for (const key in schema.properties) {
      const val = schema.properties[key] as Schema;
      lines.push("", ...generateMarkdownLevel(val, `\`${key}\``, level + "#"));
    }
    return lines;
  }

  // Type and default
  lines.push(
    `- **Type**: \`${schema.markdownType || schema.tsType || schema.type}\``
  );
  if ("default" in schema) {
    lines.push(`- **Default**: \`${JSON.stringify(schema.default)}\``);
  }
  lines.push("");

  // Title
  if (schema.title) {
    lines.push("> " + schema.title, "");
  }

  // Signuture (function)
  // if (schema.type === "function") {
  //   lines.push("```ts", genFunctionType(schema, {}), "```", "");
  // }

  // Description
  if (schema.description) {
    lines.push("", schema.description, "");
  }

  return lines;
}

/**
 * Generate a Markdown file from a TypeScript schema.
 *
 * @param schema - The TypeScript schema to convert.
 * @param file - The file to write the declaration to.
 * @param generatedBy - The tool that generated the declaration.
 * @param config - The workspace configuration.
 * @returns A promise that resolves when the file has been written.
 */
export function generateMarkdownFile(
  schema: Schema,
  file: Path,
  generatedBy = "@storm-software/untyped",
  config?: StormWorkspaceConfig
) {
  try {
    const declarations = getOutputFile(file, "md");
    writeTrace(`Writing type markdown file ${declarations}`, config);

    return writeFile(declarations, generateMarkdown(schema, generatedBy));
  } catch (error) {
    writeError(
      `Error writing markdown file for ${file.name}

Error:
${error?.message ? error.message : JSON.stringify(error)}${
        error?.stack
          ? `
Stack Trace: ${error.stack}`
          : ""
      }

Parsed schema:
${JSON.stringify(schema)}
`,
      config
    );

    throw error;
  }
}
