
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface CleanPackageExecutorSchema {
 /**
  * Entry File(s)
  * 
  * The entry file or files to build
  * 
  * @default {"default":["{sourceRoot}/index.ts"]}
  * 
  * @format path
 */
 entry?: Array<string>,

 /**
  * Output Path
  * 
  * The path to the output
  * 
  * @default "dist/{projectRoot}"
 */
 outputPath?: string,

 /**
  * TSConfig Path
  * 
  * The path to the tsconfig file
  * 
  * @default "{projectRoot}/tsconfig.json"
  * 
  * @format path
 */
 tsconfig?: string,

 /**
  * Package JSON Path
  * 
  * The path to the package.json that will be modified
  * 
  * @default "{outputPath}/package.json"
  * 
  * @format path
 */
 packageJsonPath?: string,

 /**
  * Ignored Files
  * 
  * The files to ignore
  * 
 */
 ignoredFiles?: string,

 /**
  * Fields
  * 
  * The fields to include
  * 
 */
 fields?: string,

 /**
  * Clean Read Me
  * 
  * Clean the read me
  * 
  * @default true
 */
 cleanReadMe?: boolean,

 /**
  * Clean Comments
  * 
  * Clean the comments
  * 
  * @default true
 */
 cleanComments?: boolean,
}

