
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface CleanPackageExecutorSchema {
 /**
  * Output Path
  * 
  * The path to the output
  * 
 */
 outputPath: string,

 /**
  * Package JSON Path
  * 
  * The path to the package.json
  * 
  * 
  * @format path
 */
 packageJsonPath: string,

 /**
  * Ignored Files
  * 
  * The files to ignore
  * 
 */
 ignoredFiles: string,

 /**
  * Fields
  * 
  * The fields to include
  * 
 */
 fields: string,

 /**
  * Clean Read Me
  * 
  * Clean the read me
  * 
 */
 cleanReadMe: boolean,

 /**
  * Clean Comments
  * 
  * Clean the comments
  * 
 */
 cleanComments: boolean,
}

