// This file is auto-generated by scripts/typegen.ts.
export type ConfigNames = 'storm/disables' | 'storm/ignores' | 'storm/imports' | 'storm/javascript' | 'storm/jsdoc' | 'storm/jsx' | 'storm/next' | 'storm/node' | 'storm/promise' | 'storm/react' | 'storm/react-perf' | 'storm/regexp' | 'storm/storybook' | 'storm/test' | 'storm/typescript' | 'storm/unicorn';
