name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches:
      - "main"
      - "canary"
      - "experimental"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  STORM_REPOSITORY: ${{ github.repositoryUrl }}
  STORM_WORKSPACE_ROOT: ${{ github.workspace }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: github.repository == 'storm-software/storm-ops' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/canary' || github.ref == 'refs/heads/experimental')
    steps:
      - name: Setup workspace
        uses: storm-software/action-setup@main
        with:
          package-manager: pnpm
          package-manager-version: 9.10.0
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}

      - name: Build Storm Nx-Plugin packages
        run: pnpm build-plugins
        shell: bash

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: main

      - name: Run build script
        run: pnpm build-all
        shell: bash

      - name: Add permissions to linting tools
        run: chmod a=rwx dist/packages/linting-tools/bin/lint.js
      - name: Add permissions to alex config file
        run: chmod a=rwx dist/packages/linting-tools/alex/.alexrc
      - name: Add permissions to alex ignore file
        run: chmod a=rwx dist/packages/linting-tools/alex/.alexignore

      - name: Add permissions to linting-tools package.json file
        run: chmod a=rwx packages/linting-tools/package.json
      - name: Add permissions to git-tools package.json file
        run: chmod a=rwx packages/git-tools/package.json
      - name: Add permissions to workspace-tools package.json file
        run: chmod a=rwx packages/workspace-tools/package.json
      - name: Add permissions to create-storm-workspace package.json file
        run: chmod a=rwx packages/create-storm-workspace/package.json

      - name: Add permissions to linting-tools distribution package.json file
        run: chmod a=rwx dist/packages/linting-tools/package.json
      - name: Add permissions to git-tools distribution package.json file
        run: chmod a=rwx dist/packages/git-tools/package.json
      - name: Add permissions to workspace-tools distribution package.json file
        run: chmod a=rwx dist/packages/workspace-tools/package.json
      - name:
          Add permissions to create-storm-workspace distribution package.json
          file
        run: chmod a=rwx dist/packages/create-storm-workspace/package.json

      - name: Add permissions to git tools
        run: chmod a=rwx dist/packages/git-tools/bin/git.js

      - name: Run TOML linter
        run: pnpm format-toml

      - name: Run Prettier linter
        run: pnpm format-prettier

      - name: Run Sherif linter
        run: pnpm format-sherif

      - name: Run Knip linter
        run: pnpm lint-knip

      - name: Apply fixes
        uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
        with:
          commit-message: "ci(monorepo): Apply automated CI fixes"
