---
name: Weekly codeowners cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  contents: read

jobs:
  clean-owners:
    name: clean-owners
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Run clean-owners action
        uses: github-community-projects/cleanowners@7edc384737887977379590bb94b78ef26c5cffb1 # v2.1.11
        env:
          GH_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          ORGANIZATION: storm-software
