---
name: Weekly codeowners cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  contents: read

jobs:
  clean-owners:
    name: clean-owners
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Run clean-owners action
        uses: github-community-projects/cleanowners@691d96b42929d2f1e674671c92a4250fad9932ad # v2.1.12
        env:
          GH_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          ORGANIZATION: storm-software
