---
name: Dependabot Update

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.STORM_BOT_GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    if:
      github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' ||
      github.actor == 'renovatebot' || github.actor == 'Stormie-Bot'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.STORM_BOT_GITHUB_TOKEN }}"
      # This doesn't trigger an automated merge because we require at approvals
      - name: Enable auto-merge
        run: gh pr merge --auto --squash --delete-branch "${PR_URL}"
