---
name: "Greetings"

on: [pull_request_target, issues]

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          issue-message: "Hello, I'm 🤖 Stormie-Bot! Thank you for your interest in this project! The Storm team will review this issue and reach out to you ASAP."
          pr-message: "Hello, I'm 🤖 Stormie-Bot! The Storm team sincerely appreciates your effort/interest in contributing to this project. A Storm developer will review this change and get back to you ASAP. Please feel free to reach out to the Storm team (contact@stormsoftware.com) if you have any questions/comments."
