# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      tag:
        description: Override release tag
        type: string
        required: false
      stormBot:
        description: The github username of the Storm bot
        required: false
        type: string
        default: ""
    secrets:
      githubToken:
        required: true
      npmToken:
        required: true
      cargoToken:
        required: true

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta')
    steps:
      - name: Send Slack notification - Deployment started
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "notifications"
          payload: |
            {
              "text": "Deployment for ${{ github.repository }} has started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment for ${{ github.repository }} has started",
                  "color": "1fb2a6",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.STORM_BOT_SLACK_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.githubToken }}

      - name: Setup workspace
        uses: ./.github/actions/setup
        with:
          packageManager: pnpm
          packageManagerVersion: 8.10.2
          stormBot: ${{ inputs.stormBot }}

      - name: Configure git
        run: |
          git config user.name "${{ inputs.stormBot }}"
          git config user.email "${{ inputs.stormBot }}@users.noreply.github.com"
          git config lfs.allowincompletepush true
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        shell: bash

      - name: Get appropriate base and head commits for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "main"

      - name: Set appropriate base and head commits for `nx affected` commands
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
        shell: bash

      - name: Run build script
        run: pnpm build-all
        shell: bash

      - name: Run linters scripts
        run: pnpm lint
        shell: bash

      - name: Run formatters scripts
        run: pnpm nx format
        shell: bash

      - name: Re-run build script
        run: pnpm build-all
        shell: bash

      - name: Release repository updates
        run: pnpm release --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ inputs.npmToken }}
          CARGO_REGISTRY_TOKEN: ${{ inputs.cargoToken }}
          STORM_BOT: ${{ inputs.stormBot }}
          STORM_WORKSPACE_ROOT: ${{ github.workspace }}
          STORM_REPOSITORY: ${{ github.repositoryUrl }}
          TAG: ${{ inputs.tag }}

  success:
    needs:
      - release
    if: ${{ success() }}
    name: Send success notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification - Deployment completed
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "notifications"
          update-ts: ${{ steps.release.outputs.ts }}
          payload: |
            {
              "text": "Deployment for ${{ github.repository }} has finished (Completed) \n\nPipeline Status: ${{ job.status }} \nClick here to see the full job details: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "attachments": [
                {
                  "pretext": "Deployment for ${{ github.repository }} has finished successfully",
                  "color": "087f5b",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.STORM_BOT_SLACK_TOKEN }}

  failure:
    needs:
      - release
    if: ${{ failure() }}
    name: Send failure notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification - Deployment completed
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "notifications"
          update-ts: ${{ steps.release.outputs.ts }}
          payload: |
            {
              "text": "Deployment for ${{ github.repository }} has finished (Failure) \n\nPipeline Status: ${{ job.status }}\nError: ${{ job.conclusion }}\nReason: ${{ job.cancelled }}\nConclusion: ${{ job.conclusion }}\nOutput: ${{ job.output }}\nLogs: ${{ job.logs }} \nSteps: ${{ job.steps }} \nActions: ${{ job.actions }} \nServices: ${{ job.services }} \nEnvironment: ${{ job.environment}} \nClick here to see the full job details: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "attachments": [
                {
                  "pretext": "Deployment for ${{ github.repository }} has finished with failures",
                  "color": "990000",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failure"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
