name: syncpack.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches:
      - main
      - canary
      - experimental

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  syncpack:
    name: Syncpack
    uses: ./.github/workflows/syncpack-reusable.yml
