---
name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

env:
  CI: true
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: true
  SKIP_ENV_VALIDATION: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
